### ISSUE TITLE
Create a document to describe the Google Groups specifics/how-to

### ISSUE THREAD

**Issue by andrea-kyurchiev** [InnerSourceCommons/foundation-governance#17]
https://github.com/InnerSourceCommons/foundation-governance/tree/master/how-to.  The file should explain how mailing lists work in the InnerSource Commons:

- How to request a new mailing list
- How to get added to a mailing list
- What mailing lists are out there, and what are they for
- How to interact with a mailing list

**Comment by rrrutledge** [comment]
Thank you for working on this, @andrea-kyurchiev ❗  I have a few questions, but think they would be easier to go over on a call.  Can you schedule with me at https://calendly.com/russell-rutledge?  Thank you!

**Comment by andrea-kyurchiev** [comment]
@rrrutledge just scheduled a call for the 16th there
